name: Deploy BigQuery Routine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_2 }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy Procedures
        run: |
          for file in routines/procedures/*.sql
          do
            if [ ! -s "$file" ]; then
              echo "Skipping empty file $file"
              continue
            fi

            echo "Deploying $file"

            bq query \
              --use_legacy_sql=false \
              --format=none \
              "$(cat "$file")"
          done